package fsrepo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	plugindomain "octomanger/internal/domains/plugins/domain"
)

type Repository struct {
	modulesDir string
}

func New(modulesDir string) Repository {
	return Repository{
		modulesDir: strings.TrimSpace(modulesDir),
	}
}

func (r Repository) List(ctx context.Context) ([]plugindomain.Plugin, error) {
	_ = ctx

	if r.modulesDir == "" {
		return nil, fmt.Errorf("plugins modules directory is empty")
	}

	entries, err := os.ReadDir(r.modulesDir)
	if err != nil {
		return nil, fmt.Errorf("read plugins directory: %w", err)
	}

	plugins := make([]plugindomain.Plugin, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		plugin, err := r.loadPlugin(filepath.Join(r.modulesDir, entry.Name()))
		if err != nil {
			return nil, err
		}
		if plugin == nil {
			continue // no manifest.yaml — not a plugin directory, skip silently
		}
		plugins = append(plugins, *plugin)
	}

	sort.Slice(plugins, func(i int, j int) bool {
		return plugins[i].Manifest.Key < plugins[j].Manifest.Key
	})

	return plugins, nil
}

func (r Repository) Get(ctx context.Context, key string) (*plugindomain.Plugin, error) {
	_ = ctx
	if key == "" {
		return nil, fmt.Errorf("plugin key is required")
	}

	plugin, err := r.loadPlugin(filepath.Join(r.modulesDir, key))
	if err != nil {
		return nil, err
	}
	if plugin == nil {
		return nil, fmt.Errorf("plugin manifest not found: %s", filepath.Join(r.modulesDir, key, "manifest.yaml"))
	}
	return plugin, nil
}

func (r Repository) loadPlugin(dir string) (*plugindomain.Plugin, error) {
	manifestPath := filepath.Join(dir, "manifest.yaml")
	content, err := os.ReadFile(manifestPath)
	if err != nil {
		if errorsIs(err, fs.ErrNotExist) {
			return nil, nil // not a plugin directory
		}
		return nil, fmt.Errorf("read plugin manifest: %w", err)
	}

	var manifest plugindomain.Manifest
	if err := yaml.Unmarshal(content, &manifest); err != nil {
		return nil, fmt.Errorf("decode plugin manifest %s: %w", manifestPath, err)
	}

	if strings.TrimSpace(manifest.Key) == "" {
		manifest.Key = filepath.Base(dir)
	}
	if strings.TrimSpace(manifest.Name) == "" {
		manifest.Name = manifest.Key
	}
	if strings.TrimSpace(manifest.Runtime) == "" {
		manifest.Runtime = "python"
	}
	if strings.TrimSpace(manifest.Entrypoint) == "" {
		manifest.Entrypoint = "main.py"
	}

	// Merge ui + settings from account_type.{key}.json if present (auto-generated by the Python SDK).
	atPath := filepath.Join(dir, fmt.Sprintf("account_type.%s.json", manifest.Key))
	if data, err := os.ReadFile(atPath); err == nil {
		var atFile struct {
			UI       map[string]any   `json:"ui"`
			Settings []map[string]any `json:"settings"`
		}
		if json.Unmarshal(data, &atFile) == nil {
			if manifest.UI == nil && len(atFile.UI) > 0 {
				manifest.UI = atFile.UI
			}
			if manifest.Settings == nil && len(atFile.Settings) > 0 {
				manifest.Settings = atFile.Settings
			}
		}
	}

	entrypointPath := filepath.Join(dir, manifest.Entrypoint)
	_, statErr := os.Stat(entrypointPath)

	return &plugindomain.Plugin{
		Manifest:  manifest,
		Directory: dir,
		Healthy:   statErr == nil,
	}, nil
}

func errorsIs(err error, target error) bool {
	return errors.Is(err, target)
}
