package plugindomain

type Manifest struct {
	Key            string            `yaml:"key" json:"key"`
	Name           string            `yaml:"name" json:"name"`
	Version        string            `yaml:"version" json:"version"`
	Description    string            `yaml:"description" json:"description"`
	Runtime        string            `yaml:"runtime" json:"runtime"`
	Entrypoint     string            `yaml:"entrypoint" json:"entrypoint"`
	Capabilities   []string          `yaml:"capabilities" json:"capabilities"`
	Actions        []ManifestAction  `yaml:"actions" json:"actions"`
	AccountSchema  map[string]any    `yaml:"account_schema" json:"account_schema"`
	SettingsSchema map[string]any    `yaml:"settings_schema" json:"settings_schema"`
	// UI and Settings are loaded from account_type.{key}.json (auto-generated by the Python SDK).
	UI       map[string]any   `yaml:"ui,omitempty"       json:"ui,omitempty"`
	Settings []map[string]any `yaml:"settings,omitempty" json:"settings,omitempty"`
	Metadata map[string]string `yaml:"metadata,omitempty" json:"metadata,omitempty"`
}

type ManifestAction struct {
	Key         string   `yaml:"key" json:"key"`
	Name        string   `yaml:"name" json:"name"`
	Description string   `yaml:"description,omitempty" json:"description,omitempty"`
	Modes       []string `yaml:"modes,omitempty" json:"modes,omitempty"`
}

type Plugin struct {
	Manifest  Manifest `json:"manifest"`
	Directory string   `json:"directory"`
	Healthy   bool     `json:"healthy"`
}

type ExecutionRequest struct {
	Mode    string         `json:"mode"`
	Action  string         `json:"action"`
	Input   map[string]any `json:"input,omitempty"`
	Context map[string]any `json:"context,omitempty"`
}

type ExecutionEvent struct {
	Type     string         `json:"type"`
	Message  string         `json:"message,omitempty"`
	Progress int            `json:"progress,omitempty"`
	Data     map[string]any `json:"data,omitempty"`
	Error    string         `json:"error,omitempty"`
}
